# 2.1 数据操作

## 2.1.1 入门

In [25]:
# 导入torch库
import torch

In [8]:
# 创建整型向量
int_vector = torch.arange(15)
int_vector

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
float_tensor = torch.arange(15, dtype=torch.float32)
float_tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14.])

In [21]:
shape = int_vector.shape
numel = int_vector.numel()
shape, numel

(torch.Size([15]), 15)

In [85]:
manual = int_vector.reshape(3, 5)

auto = int_vector.reshape(-1,5)

print("auto:", auto)

print("manual:", manual)

auto: tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
manual: tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [33]:
zeros_tensor = torch.zeros(2, 5)
zeros_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [36]:
ones_tensor = torch.ones(4, 4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
l = [
    [1, 2, 3],
    [4, 5, 6]
    ]
list_to_tensor = torch.tensor(l)
list_to_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
randn_tensor = torch.randn(3,3)
randn_tensor

tensor([[ 0.6991, -1.7792,  0.7816],
        [-0.2696, -0.7418, -1.8899],
        [-0.1762, -0.8113,  0.5235]])

## 2.1.2 运算符

In [42]:
x = torch.randn(3, 4)
y = torch.randn(3, 4)
x, y

(tensor([[ 1.4601, -0.7015,  0.7316,  0.2269],
         [-2.7876, -1.4268, -0.1197,  0.6829],
         [-0.4303, -0.5335, -0.9017, -2.7408]]),
 tensor([[ 0.7715,  0.2767,  1.4215, -1.6730],
         [ 1.0291,  0.6006,  0.5876, -0.1903],
         [-0.0251, -1.2935,  0.3005,  0.1139]]))

In [43]:
# 加法
add = x + y
add

tensor([[ 2.2316, -0.4248,  2.1532, -1.4461],
        [-1.7585, -0.8263,  0.4679,  0.4927],
        [-0.4554, -1.8270, -0.6011, -2.6270]])

In [45]:
# 减法
sub = x - y
sub

tensor([[ 0.6885, -0.9782, -0.6899,  1.8999],
        [-3.8168, -2.0274, -0.7073,  0.8732],
        [-0.4052,  0.7600, -1.2022, -2.8547]])

In [44]:
# 乘法
mul = x * y
mul

tensor([[ 1.1265, -0.1941,  1.0401, -0.3796],
        [-2.8688, -0.8569, -0.0703, -0.1299],
        [ 0.0108,  0.6901, -0.2710, -0.3122]])

In [46]:
# 除法
div = x / y
div

tensor([[  1.8924,  -2.5352,   0.5147,  -0.1356],
        [ -2.7087,  -2.3758,  -0.2037,  -3.5893],
        [ 17.1433,   0.4124,  -3.0003, -24.0650]])

In [50]:
# 幂运算 （底数>0）
exp = x ** y
exp

tensor([[ 1.3391,     nan,  0.6413, 11.9564],
        [    nan,     nan,     nan,  1.0753],
        [    nan,     nan,     nan,     nan]])

In [86]:
# torch.cat()函数---张量之间拼接

# dim=0 增加行向量
cat_row = torch.cat((x, y), dim=0)

# dim=1 增加列向量
cat_col = torch.cat((x, y), dim=1)
print("cat_row:\n",cat_row)
print("cat_col:\n", cat_col)

# 若增加行向量，矩阵的列数必须保持相同
row_x = torch.randn(2, 3)
row_y = torch.randn(4, 3)
cat_increase_row = torch.cat((row_x, row_y),dim=0)
print("cat_increase_row:\n", cat_increase_row)

# 若增加列向量，矩阵的行数必须保持相同
col_x = torch.randn(3, 4)
col_y = torch.randn(3, 5)
cat_increase_col = torch.cat((col_x, col_y), dim=1)
print("cat_increase_col:\n", cat_increase_col)

cat_row:
 tensor([[ 1.4601, -0.7015,  0.7316,  0.2269],
        [-2.7876, -1.4268, -0.1197,  0.6829],
        [-0.4303, -0.5335, -0.9017, -2.7408],
        [ 0.7715,  0.2767,  1.4215, -1.6730],
        [ 1.0291,  0.6006,  0.5876, -0.1903],
        [-0.0251, -1.2935,  0.3005,  0.1139]])
cat_col:
 tensor([[ 1.4601, -0.7015,  0.7316,  0.2269,  0.7715,  0.2767,  1.4215, -1.6730],
        [-2.7876, -1.4268, -0.1197,  0.6829,  1.0291,  0.6006,  0.5876, -0.1903],
        [-0.4303, -0.5335, -0.9017, -2.7408, -0.0251, -1.2935,  0.3005,  0.1139]])
cat_increase_row:
 tensor([[-0.8478,  1.2235, -0.0685],
        [ 0.7174,  0.5485, -0.4737],
        [ 0.9451, -0.3455, -0.1643],
        [ 0.7222, -1.0900,  0.6038],
        [-1.1996, -1.0971,  0.2142],
        [-0.1563, -0.4311, -1.2022]])
cat_increase_col:
 tensor([[ 1.4854, -0.0608, -0.5504, -0.7944, -0.8707, -0.5543,  2.1998, -0.3740,
         -0.1084],
        [ 0.1755,  1.0293, -0.7239,  0.4633, -0.3182, -1.3267,  1.0856,  0.3860,
         -0.05

In [64]:
# 使用sum()方法对tensor中所有元素求和,并返回一个张量
sum_x = torch.randn(3, 4)
sum_tensor = sum_x.sum()
sum_tensor

tensor(2.6188)

## 2.1.3 广播机制

In [74]:
x_broad = torch.randn(2)
y_broad = torch.randn(3,2,2)
x_broad + y_broad

tensor([[[ 1.3904, -1.2378],
         [-0.2035, -0.2642]],

        [[ 1.9737, -1.0751],
         [ 0.4408, -0.6978]],

        [[-0.0371, -0.3069],
         [ 1.2287,  0.2305]]])

## 2.1.4 索引和切片

In [75]:
idx_tensor = torch.arange(12).reshape(3, 4)
idx_tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [76]:
# 同时获取多个元素
get_element = idx_tensor[:2, :]
get_elemen

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

## 2.1.5 节省内存

In [81]:
memory_x = torch.randn(2, 3)
memory_y = torch.randn(2, 3)
befor_x_id = id(memory_x)
print("before_x_id:", befor_x_id)
memory_x = memory_x + memory_y
print("add memory x id:", id(memory_x))
memory_x[:] = memory_x + memory_y
print("[:] add id:", id(memory_x))

before_x_id: 140312240590176
add memory x id: 140312229164144
[:] add id: 140312229164144


## 2.1.6 转换为其他Python对象

In [83]:
# 使用张量的numpy()方法，将张量转换为numpy.ndarray类型
convert_tensor = torch.randn(3, 4)
tensor_to_numpy = convert_tensor.numpy()
tensor_to_numpy

array([[ 0.95006216, -0.5165921 ,  0.34783304,  0.5194973 ],
       [ 0.09277122,  0.26368752, -1.8891605 ,  0.14917013],
       [ 2.4105961 , -0.47035468, -1.0013242 , -0.968069  ]],
      dtype=float32)

In [84]:
# 使用torch.tensor()函数将numpy.ndarray类型转换为张量
numpy_to_tensor = torch.tensor(tensor_to_numpy)
numpy_to_tensor

tensor([[ 0.9501, -0.5166,  0.3478,  0.5195],
        [ 0.0928,  0.2637, -1.8892,  0.1492],
        [ 2.4106, -0.4704, -1.0013, -0.9681]])

## 练习

In [101]:
# ==
logic_x = torch.randn(3, 4)
logic_y =  torch.randn(3, 4)
logic_x == logic_y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [102]:
# <
logic_x < logic_y

tensor([[False,  True, False, False],
        [False, False,  True, False],
        [ True,  True,  True,  True]])

In [103]:
# >
logic_x > logic_y

tensor([[ True, False,  True,  True],
        [ True,  True, False,  True],
        [False, False, False, False]])

In [106]:
# 测试logic是否满足广播机制
logic_broad_x = torch.randn(1, 2, 1)
logic_broad_y = torch.randn(3, 1, 3)
logic_broad_x < logic_broad_y

tensor([[[ True,  True,  True],
         [False,  True, False]],

        [[ True, False, False],
         [ True, False, False]],

        [[ True, False,  True],
         [ True, False, False]]])

In [108]:
pra_broad_x = torch.randn(1, 3, 5)
pra_broad_y = torch.randn(4,3, 1)
pra_broad_x + pra_broad_y

tensor([[[ 0.8368, -0.3867,  0.4151,  1.1498,  1.8494],
         [-0.6255, -2.0392, -0.7277,  0.4984, -0.9893],
         [-0.8679,  0.1367,  1.0319,  1.6718,  1.9329]],

        [[ 0.0812, -1.1423, -0.3405,  0.3941,  1.0937],
         [ 1.4849,  0.0711,  1.3827,  2.6088,  1.1211],
         [-2.7408, -1.7363, -0.8411, -0.2011,  0.0600]],

        [[ 0.5131, -0.7104,  0.0914,  0.8260,  1.5256],
         [ 0.2214, -1.1924,  0.1192,  1.3453, -0.1424],
         [-0.4556,  0.5489,  1.4441,  2.0841,  2.3452]],

        [[-0.3596, -1.5831, -0.7813, -0.0467,  0.6529],
         [ 0.7627, -0.6510,  0.6605,  1.8867,  0.3990],
         [-0.1842,  0.8203,  1.7155,  2.3555,  2.6166]]])

# 2.2 数据预处理

## 2.2.1读取数据

In [16]:
data_file = "./house_tiny.csv"
with open(data_file, "w") as f:
    f.write("NumRooms, Alley, Price\n")
    f.write("NaN, Pave, 127800\n")
    f.write("2, NaN, 106000\n")
    f.write("4, NaN, 178100\n")
    f.write("NA, NaN, 140000\n")

In [17]:
import pandas as pd
data = pd.read_csv(data_file, encoding="utf-8")
data

NumRooms  Alley   Price
0       NaN   Pave  127800
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN    NaN  140000

## 2.2.2 处理缺失值

In [18]:
input_data, output_data = data.iloc[:, :2], data.iloc[:, 2]
# 使用插值法填充数据
input_data["NumRooms"] = input_data["NumRooms"].fillna(input_data["NumRooms"].mean())

In [35]:
input_data = pd.get_dummies(input_data, dummy_na=True)
input_data

NumRooms   Alley_ NaN   Alley_ Pave
0       3.0        False          True
1       2.0         True         False
2       4.0         True         False
3       3.0         True         False

## 2.2.3 DataFrame、Serise类型转换为张量

In [42]:
pd_x_to_tensor = torch.tensor(input_data.to_numpy(dtype=float))
pd_y_to_tensor = torch.tensor(output_data.to_numpy(dtype=float))
print("pd_x_to_tensor:\n",pd_x_to_tensor)
print("pd_y_to_tensor:\n", pd_y_to_tensor)


pd_x_to_tensor:
 tensor([[3., 0., 1.],
        [2., 1., 0.],
        [4., 1., 0.],
        [3., 1., 0.]], dtype=torch.float64)
pd_y_to_tensor:
 tensor([127800., 106000., 178100., 140000.], dtype=torch.float64)


In [46]:
# 在to_numpy()不指定转换的数据类型
try:
    torch.tensor(input_data.to_numpy())
except TypeError as error:
    print(error)

can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.


In [47]:
# 在to_numpy()不指定转换的数据类型，在torch.tensor()中指定数据转换类型
try:
    torch.tensor(input_data.to_numpy(), dtype=torch.float32)
except TypeError as error:
    print(error)

can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.


# 2.3线性代数

# 2.4 微积分

# 2.5 自动微分

# 2.6 概率